version: "3.9"

services:
  web:
    build: .
    command: 
      sh -c "python manage.py migrate --noinput &&
            daphne -b 0.0.0.0 -p 8000 debateRoom.asgi:application"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=1
      - POSTGRES_DB=debate_db
      - POSTGRES_USER=vasundhara
      - POSTGRES_PASSWORD=vasu1724
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: debate_db
      POSTGRES_USER: vasundhara
      POSTGRES_PASSWORD: vasu1724
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine

volumes:
  postgres_data:
