# Generated by Django 5.2.1 on 2025-06-18 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('moderator', 'Moderator'), ('debater', 'Debater'), ('audience', 'Audience')], default='audience', max_length=64),
        ),
    ]
