# Generated by Django 5.2.1 on 2025-05-26 08:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='debateround',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='debateround',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
