# Generated by Django 5.2.1 on 2025-05-30 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0002_debateround_end_time_debateround_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='debateroom',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
