# Generated by Django 5.2.1 on 2025-06-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0003_debateroom_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='debateroom',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='DebateRound',
        ),
    ]
