# Generated by Django 5.2.1 on 2025-06-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0005_debateroom_winner_debateroom_winner_declared_vote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomparticipant',
            name='role',
            field=models.CharField(choices=[('moderator', 'Moderator'), ('debater', 'Debater'), ('audience', 'Audience')], max_length=10),
        ),
    ]
