# Generated by Django 5.2.1 on 2025-06-20 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0006_alter_roomparticipant_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='debateroom',
            old_name='format',
            new_name='debate_format',
        ),
    ]
