# Generated by Django 5.2.1 on 2025-06-22 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debates', '0007_rename_format_debateroom_debate_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debateroom',
            name='timer_per_round',
            field=models.IntegerField(default=180),
        ),
    ]
